SmithASP/Controllers/CryptoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SmithASP.Models;
using SmithASP.ViewModels;

namespace SmithASP.Controllers
{
    public class CryptoController : Controller
    {

        private readonly CryptogramDbContext _context;

        public CryptoController(CryptogramDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            EncryptionMethodViewModel e = new EncryptionMethodViewModel();
            //Select list for dropdown
            SelectList methods = new SelectList(_context.EncryptionMethods.OrderBy(x => x.EncryptionMethodId),
                "EncryptionMethodId", "Name");
            e.MyMethods = methods;
            return View(e);
        }

        public IActionResult Select_type(String type)
        {
            EncryptionMethod e = _context.EncryptionMethods.Find(Convert.ToInt32(type));
            //opens up a view with the same name as the cipher type. i.e Caesar, Transposition
            return View(e.Name);
        }

        [HttpPost]
        public IActionResult Caesar_Output(Cryptogram cryptogram)
        {
            if (ModelState["message"].Errors.Count == 0 && ModelState["key"].Errors.Count == 0)
            {
                String symbols = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890!?. ";
                String translatedMessage = "";
                int symbolIndex;
                int key = Convert.ToInt32(cryptogram.key);

                //loop through each character in the message
                foreach (char s in cryptogram.message)
                {
                    //if the character is in the symbols proceed
                    if (symbols.Contains(s))
                    {
                        symbolIndex = symbols.IndexOf(s) + key;
                        if (symbolIndex >= symbols.Length)
                        {
                            symbolIndex = symbolIndex - symbols.Length;
                        }
                        else if (symbolIndex < 0)
                        {
                            symbolIndex = symbolIndex + symbols.Length;
                        }
                        translatedMessage += symbols[symbolIndex];
                    }
                }
                cryptogram.result = translatedMessage;
                return View("Details", cryptogram);
            }
            return View("Caesar");
        }
    }
}

SmithASP/Views/Crypto/Caesar.cshtml
@model SmithASP.Models.Cryptogram;
@{
    ViewData["Title"] = "Caesar";
}

<form asp-controller="Crypto" asp-action="Caesar_Output" method="post" role="form">
    <label asp-for="message" placeholder="Cleartext Message">Message</label>
    <input asp-for="message" class="form-control" />
    <span asp-validation-for="message"></span>
    <br />
    <label asp-for="key">Key</label>
    <input asp-for="key" placeholder="Encryption Key Number" class="form-control" />
    <span asp-validation-for="key"></span>
    <br />
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

SmithASP/Views/Crypto/Details.cshtml
@model SmithASP.Models.Cryptogram

@{
    ViewData["Title"] = "Details";
}
<div>
    <h4>Cryptogram</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            <label asp-for="message" class="col-sm-2 col-form-label">Message: </label>
        </dt>
        <dd class="col-sm-10">
            <input asp-for="message" class="form-control" readonly />
        </dd>
        <dt class="col-sm-2">
            <label asp-for="result" class="col-sm-2 col-form-label">Result: </label>
        </dt>
        <dd class="col-sm-10">
            <input asp-for="result" class="form-control" readonly />
        </dd>
        <dt class="col-sm-2">
            <label asp-for="key" class="col-sm-2 col-form-label">Key: </label>
        </dt>
        <dd class="col-sm-10">
            <input asp-for="key" class="form-control" readonly />
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.CryptogramId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

SmithASP/Views/Crypto/index.cshtml
@model EncryptionMethodViewModel
@{
    ViewData["Title"] = "Caesar";
}

    <div>
        <h2>Create A Cryptogram</h2>
        @using (Html.BeginForm("Select_type", "Crypto", FormMethod.Post))
        {

            @Html.DropDownList("type", Model.MyMethods);
            <input class="submit" type="submit" value="submit" />
        }
    </div>