SmithASP/Models/Workout/Exercise.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SmithASP.Models.Workout
{

    public class Exercise
    {
        public Exercise(int id, string name, string userName)
        {
            Id = id;
            Name = name;
            UserName = userName;
        }

        public Exercise()
        {
        }

        [Key]
        public int Id { get; set; }
        [Required]
        public string UserName { get; set; }
        [Required]
        public string Name { get; set; }
    }
}

SmithASP/Models/Workout/ExerciseMuscleGroup.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SmithASP.Models.Workout
{
    public class ExerciseMuscleGroup
    {
        public ExerciseMuscleGroup()
        {

        }
        public ExerciseMuscleGroup(int exerciseId, int muscleGroupId)
        {
            ExerciseId = exerciseId;
            MuscleGroupId = muscleGroupId;
        }
        public int ExerciseId { get; set; }
        public Exercise Exercise { get; set; }
        public int MuscleGroupId { get; set; }
        public MuscleGroup MuscleGroup { get; set; }
    }
}

SmithASP/Models/Workout/MuscleGroup.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SmithASP.Models.Workout
{
    public class MuscleGroup
    {
        [Key]
        public int MuscleGroupId { get; set; }
        [Required]
        public string Name { get; set; }
    }
}

SmithASP/Models/Workout/ScheduledWorkout.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SmithASP.Models.Workout
{
    public class ScheduledWorkout
    {
        public int Id { get; set; }
        public Workout Workout { get; set; }
        public int WorkoutId { get; set; }
        public string AspNetUserId { get; set; }
        public DateTime DateAndTime { get; set; }
    }
}

SmithASP/Models/Workout/Vitals.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SmithASP.Models.Workout
{
    public class Vitals
    {
        [Key]
        public int Id { get; set; }
        public string AspNetUserId { get; set; }
        public int BP { get; set; }
        public int HR { get; set; }
        public DateTime Time { get; set; }

    }
}

SmithASP/Models/Workout/Workout.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace SmithASP.Models.Workout
{
    public class Workout
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        public string AspNetUserId { get; set; }
        [Required]
        public String TargetDuration { get; set; }
        public String Description { get; set; }
    }
}

SmithASP/Models/Workout/WorkoutExercise.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SmithASP.Models.Workout
{
    public class WorkoutExercise
    {
        public int ExerciseId { get; set; }
        public Exercise Exercise { get; set; }
        public int WorkoutId { get; set; }
        public Workout Workout { get; set; }
        public int Sets { get; set; }
        public int Reps { get; set; }
        public float Weight { get; set; }
        //Type could vary depending on how an exercise is being performed. Generally this is not the case but I think it is better off
        //Stored here so that certain exercises can be more flexible in their type
        public string Type { get; set; }
        //Running won't require rest time, lifting time should have pre determined rest times between each set
        //Advanced or scaling rest times can be added once a high mastery of regular exercises is reached
        public DateTime RestTime { get; set; }
        //The next three fields are used for post workout record keeping
        //Including timings will benefit advanced users who are aiming to achieve reps/time results

    }
}

SmithASP/Controllers/WorkoutController.cs
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using SmithASP.Models;
using SmithASP.Models.DbContexts;
using SmithASP.Models.Workout;
using SmithASP.ViewModels;
using SmithASP.ViewModels.WorkoutViewModels;

namespace SmithASP.Controllers
{
    public class WorkoutController : Controller
    {

        private readonly WorkoutContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public WorkoutController(WorkoutContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public IActionResult Index()
        {

            var userId = _userManager.GetUserId(User);
            DashboardViewModel DVM = new DashboardViewModel();
            DVM.ExerciseViewModel.MuscleGroups = _context.MuscleGroups.ToList();
            DVM.ScheduledWorkouts.ScheduledWorkouts = new ScheduledWorkout[3];
            DVM.Exercises = _context.GetExercisesForUser(User.Identity.Name);
            //var workouts = _context.Workouts.Where(x => x.AspNetUserId == userId).ToList();
            return View(DVM);
        }

        public IActionResult CreateWorkout()
        {
            Exercise[] allExercises = _context.Exercises.ToArray();
            WorkoutCreationViewModel vm = new WorkoutCreationViewModel();
            vm.allExercises = allExercises;
            return View(vm);
        }

        public IActionResult CreateExercise(ExerciseViewModel view)
        {
            string[] allIds = Request.Form["muscleId"];
            EntityEntry e = _context.Exercises.Add(new Exercise() { Name = view.Name, UserName = User.Identity.Name});
            foreach (string muscleIdString in allIds)
            {
                int muscleId = Convert.ToInt32(muscleIdString);
                _context.ExerciseMuscleGroups.Add(new ExerciseMuscleGroup(e.CurrentValues.GetValue<int>("Id"), muscleId));
            }
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

SmithASP/ViewComponents/LoginViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SmithASP.ViewComponents
{
    public class LoginViewComponent : ViewComponent
    {

        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }

    }
}

SmithASP/Views/Workout/CreateWorkout.cshtml
@model SmithASP.ViewModels.WorkoutViewModels.WorkoutCreationViewModel

<h2 class="ui dividing header">New Workout</h2>
<br />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateWorkout" class="ui form">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="field">
                <label asp-for="WorkoutName" class="control-label"></label>
                <input asp-for="WorkoutName" class="form-control" />
                <span asp-validation-for="WorkoutName" class="text-danger"></span>
            </div>
            <div class="two fields">
                <div class="field">
                    <label asp-for="Duration" class="control-label"></label>
                    <input asp-for="Duration" type="time" class="form-control" />
                    <span asp-validation-for="Duration" class="text-danger"></span>
                </div>
            </div>
            <div class="field">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <br /><br />
            <h3 class="ui dividing header">Exercise List</h3>
            <div class="two fields">
                <div class="field">
                    <table id="ExerciseTable" class="ui celled striped table">
                        <thead>
                            <tr>
                                <th>Sequence</th>
                                <th>Name</th>
                                <th>Type</th>
                                <th>Sets</th>
                                <th>Reps</th>
                                <th>Weight</th>
                                <th>Rest Time</th>
                            </tr>
                        </thead>
                    </table>
                </div>
                <div class="field">
                    <div class="ui segment">
                        <label>Name</label>
                        <select class="ui dropdown">
                            @foreach (Exercise e in Model.allExercises)
                            {
                                <option value="@e.Name">@e.Name</option>
                            }
                        </select>
                    </div>
                    <div class="ui segment">
                        <label>Type</label>
                        <select class="ui dropdown">
                            <option value="Cardio">Cardio</option>
                            <option value="Weight Lifting">Weight Lifting</option>
                            <option value="Cross Fitness">Cross Fitness</option>
                        </select>
                    </div>
                    <div class="ui segment">
                        <div class="two fields">
                            <div class="field">
                                <label>Sets</label><input type="text" placeholder="Number of Sets" />
                            </div>
                            <div class="field">
                                <label>Reps</label><input type="text" placeholder="Number of Reps" />
                            </div>
                        </div>
                    </div>
                    <div class="ui segment">
                        <label>Weight</label><input type="text" placeholder="Weight in pounds" />
                    </div>
                    <div class="ui segment">
                        <label>Rest Time</label><input type="time" />
                    </div>
                    <button id="addExercise" type="button" class="ui button blue">Add Exercise</button>
                </div>
            </div>
            <br />
            <div class="ui segment">
                <div class="field">
                    <div class="ui toggle checkbox">
                        <input type="checkbox" name="SaveWorkout" asp-for="SaveWorkout" />
                        <label>Save to profile workouts?</label>
                    </div>
                </div>
            </div>
            <div class="field">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

SmithASP/Views/Workout/_CreateExercise.cshtml
@model SmithASP.ViewModels.WorkoutViewModels.ExerciseViewModel;

<form asp-controller="Workout" asp-action="CreateExercise">
    <h3>Exercise Creator</h3>
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <table id="CreateExerciseTable">
        <tr>
            <td><input asp-for="Name" class="form-control" placeholder="Exercise Name" /></td>
            <td><input type="submit" value="Create" class="Submit" /></td>
        </tr>
        <tr>
            <td>
                <select id="MuscleGroup">
                    @foreach (MuscleGroup m in Model.MuscleGroups)
                    {
                        <option value="@m.MuscleGroupId">@m.Name</option>
                    }
                </select>
            </td>
            <td><button type="button" id="AddMuscleGroup">Add Muscle</button></td>
        </tr>
    </table>
    <h4 class="underline">Muscle Groups</h4>
    <table id="ExerciseMuscleGroupTable"></table>
    <script src="~/lib/CreateExercise.js"></script>
    <span asp-validation-for="Name" class="text-danger"></span>
</form>

SmithASP/Views/Workout/_DashboardWorkoutTable.cshtml
@model SmithASP.ViewModels.WorkoutViewModels.ScheduledWorkoutViewModel
@*

*@

<table class="ui celled table">
    <tr>
        <th>Workout</th>
        <th>Date</th>
        <th>Duration</th>
        <th>Description</th>
        <th>View</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>
    @*if (Model != null)
    {
        @foreach (var w in Model.ScheduledWorkouts)
        {
            <tr>
                <th>@w.Workout.Name</th>
                <th></th>
                <th></th>
                <th>@w.Workout.Description</th>
                <th><form asp-controller="Workout" asp-action="View" asp-route="@w.Id"><button class="ui button" type="submit">View</button></form></th>
                <th><form asp-controller="Workout" asp-action="Edit" asp-route="@w.Id"><button class="ui button" type="submit">Edit</button></form></th>
                <th><form asp-controller="Workout" asp-action="Delete" asp-route="@w.Id"><button class="ui button" type="submit">Delete</button></form></th>
            </tr>
        }
    }
        *@
</table>

SmithASP/Views/Workout/_TopExercises.cshtml
@model IEnumerable<SmithASP.ViewModels.WorkoutViewModels.ExerciseViewModelV2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Exercise
            </th>
            <th>
                Muscle Groups
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.Exercise.Name
                </td>
                <td>
                    @foreach(MuscleGroup m in item.MuscleGroups)
                    {
                        @m.Name
                    }
                </td>
                <td>
                </td>
            </tr>
        }
    </tbody>
</table>

SmithASP/Views/Workout/index.cshtml
@model SmithASP.ViewModels.WorkoutViewModels.DashboardViewModel
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@if (SignInManager.IsSignedIn(User))
{
    <h1>Welcome to your exercise buddy!</h1>
    <br />
    <div class="WorkoutPanel">
        <h2>Workouts</h2>
        <div class="ScheduledWorkouts">
            <h3>Your Schedule</h3>
            @await Html.PartialAsync("_DashboardWorkoutTable", Model.ScheduledWorkouts)
        </div>
        <div class="ScheduleWorkoutFromExisting">
            <form asp-controller="Workout" asp-action="AddExistingWorkout">
                <button class="ui button">Add Saved Workout</button>
            </form>
        </div>
        <form asp-controller="Workout" asp-action="CreateWorkout"><button class="ui button">Add New Workout</button></form>
    </div>


    <div class="ExercisePanel">
        <div class="PanelSection">
            @await Html.PartialAsync("_TopExercises", Model.Exercises)
        </div>
        <div class="PanelSection">
            @await Html.PartialAsync("_CreateExercise", Model.ExerciseViewModel)
        </div>
    </div>

}
else
{
    @await Component.InvokeAsync("Login")
    <h1>Please login or <a href="/Home/Register">register</a> an account to use this feature.</h1>
}